import { NextResponse } from "next/server";
import { getDatabase } from "../../lib/mongodb";

const parishes = [
  "Adyapady",
  "Agrar",
  "Allipade",
  "Ammembal",
  "Anegudde",
  "Angelore",
  "Anthonykatte",
  "Arva",
  "Ashoknagar",
  "Badyar",
  "Bajal",
  "Bajjodi",
  "Bajpe",
  "Bambil",
  "Bannur",
  "Bantwal",
  "Bejai",
  "Bela",
  "Belloor",
  "Belthangady",
  "Belvai",
  "Bendur",
  "Bola",
  "Bolkunje",
  "Bondel",
  "Borimar",
  "Bovikana",
  "Cascia",
  "Cordel",
  "Delanthabettu",
  "Derebail",
  "Eliarpadav",
  "Fajir",
  "Farla",
  "Ferar",
  "Fermai",
  "Gantalkatte",
  "Gardady",
  "Gurpur - Kaikamba",
  "Hosabettu",
  "Indubettu",
  "Jeppu",
  "Kadaba",
  "Karady (Vijayadka)",
  "Kasargod",
  "Kateel",
  "Katipalla",
  "Kayyar",
  "Kelarai",
  "Kinnigoli",
  "Kirem",
  "Kokkada",
  "Kollangana",
  "Komangala",
  "Kulur",
  "Kumbla",
  "Kuppepadav",
  "Lawrencenagar Permude",
  "Loretto",
  "Madanthyar",
  "Manela",
  "Maniampare",
  "Manjeshwar",
  "Manjotti",
  "Mariashram - Shanthivana",
  "Maril",
  "Milagres - Mangalore",
  "Miyapadavu",
  "Mogarnad",
  "Moodbidri - Alangar",
  "Moodbidri Town",
  "Mudipu",
  "Mukka",
  "Mulky",
  "Nainadu",
  "Nala - Mavinakatte",
  "Narampady",
  "Naravi",
  "Neermarga",
  "Neerude",
  "Nellikar",
  "Nellyady",
  "Niddodi",
  "Nidpalli",
  "Nirkan",
  "Nithyadarnagar",
  "Omzoor",
  "Pakshikere",
  "Paladka",
  "Paldane",
  "Panir",
  "Panja",
  "Pavoor Uliya",
  "Pavur",
  "Permannur",
  "Permude",
  "Peruvai",
  "Pezar",
  "Puttur",
  "Ranipura",
  "Rosario",
  "Salethur",
  "Sampaje",
  "Sampige",
  "Saverapura",
  "Shakthinagar",
  "Shambur",
  "Shirthady",
  "Siddakatte",
  "Sullia",
  "Surathkal",
  "Taccode",
  "Thannirbavi",
  "Thodambila",
  "Thokur",
  "Ujire",
  "Ukkinadka",
  "Uppinangady",
  "Urwa",
  "Valencia",
  "Vamadapadav",
  "Vamanjoor",
  "Venur",
  "Vittal",
  "Vorkady",
];

export async function GET() {
  try {
    const db = await getDatabase();

    const collection = db.collection("parishes");

    await collection.deleteMany({});

    const documents = parishes.map((name, index) => ({
      parishNumber: index + 1,
      name,
      createdAt: new Date(),
    }));

    await collection.insertMany(documents);

    return NextResponse.json({
      success: true,
      message: "Parishes seeded successfully",
      count: documents.length,
    });
  } catch (error) {
    console.error(error);

    return NextResponse.json(
      {
        success: false,
        error: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 }
    );
  }
}